### PR TITLE
Fix sbt_workspaceRoot is empty

### LINKED ISSUE #23: ${workspaceRoot} is empty when no file is open
`${workspaceRoot}` is empty when no file is open.

Here are some details about the issue:

https://github.com/Microsoft/vscode/issues/28620

Here are some screenshots:

tasks json

### PR DESCRIPTION
**Pull request by szabolcsdombi**
- fix sbt_workspaceRoot is empty
- fix #23

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @cprogrammer1994!

**Comment by guardrex** [comment]
I'll make a note that I need to update the extensions gallery with a new version that includes this change, but I won't be able to get to that for a few days ..... *swamped with work* as usual. 😅

**Comment by szabolcsdombi** [comment]
I hope you can find the time to make a new release. Thank you for merging this, it will be very useful for me.

**Comment by szabolcsdombi** [comment]
can you make a release?

**Comment by guardrex** [comment]
Sorry for the delay. I'm slammed with work from my day job. I get 100% of my income from my contract ... and 0% from this. I'll get back to this asap.

In the meantime, you can use the updated extension (after the PR merge) locally ...

> If you want to install it manually directly from this repo, take the entire status-bar-tasks folder and place it into your user profile *.vscode/extensions* folder. This will make it available to any project you open in VS Code.

In your case, you'd uninstall the extension that you installed via the gallery first. Then do that :point_up: and it should work fine (in theory!).

**Comment by szabolcsdombi** [comment]
Sorry for bothering, you I will install the extension from source as you mentioned:

> If you want to install it manually directly from this repo, take the entire status-bar-tasks folder and place it into your user profile .vscode/extensions folder. This will make it available to any project you open in VS Code.

Thank you for your help!

**Comment by guardrex** [comment]
> Sorry for bothering

No problem at all. I wish I could've done it last weekend. I *will* try to get this done asap. This upcoming weekend looks a little better than last, but I'll also see how the next couple of days go.

**Pull request merged**
